/*
 * Copyright 2013-2015 Denis Meyer
 * All rights reserved.
 */
package de.calltopower.mhri.util.conf;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.Charset;
import java.util.Properties;
import org.apache.log4j.Logger;

/**
 * Configuration
 *
 * @date unknown
 *
 * @author Denis Meyer (calltopower88@gmail.com)
 */
public class Configuration {

    private static final Logger logger = Logger.getLogger(Configuration.class);
    private Properties props;

    public Configuration(Properties props) {
        this.props = props;
    }

    public Properties getProperties() {
        return props;
    }

    public void setProperties(Properties props) {
        this.props = props;
    }

    public boolean store(String file) {
        OutputStreamWriter out = null;
        try {
            out = new OutputStreamWriter(new FileOutputStream(file), Charset.forName("UTF-8"));
            props.store(out, "Auto-generated by MHRI");
            return true;
        } catch (IOException ex) {
            logger.error("Configuration::store - IOException: " + ex.getMessage());
        } finally {
            if (out != null) {
                try {
                    out.close();
                } catch (IOException ex) {
                }
            }
        }
        return false;
    }

    public String get(String key) {
        String value = props.getProperty(key);
        if (value == null) {
            logger.error("Configuration::get - Configuration key '" + key + "' not found, returning empty String.");
            return "";
        } else {
            return value;
        }
    }

    public void set(String key, String value) {
        props.setProperty(key, value);
    }
}
