/*
 * Copyright 2013-2015 Denis Meyer
 * All rights reserved.
 */
package de.calltopower.mhri.gui;

import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import org.apache.log4j.Logger;
import de.calltopower.mhri.util.Constants;

/**
 * UpdateCheck
 *
 * @date 07.07.2013
 *
 * @author Denis Meyer (calltopower88@gmail.com)
 */
public class UpdateCheck extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(UpdateCheck.class);

    public UpdateCheck() {
        initComponents();

        this.setTitle(Constants.getInstance().getLocalizedString("UpdateCheck"));
        this.jLabel2.setText(Constants.getInstance().getLocalizedString("CheckingForUpdates"));

        this.label_imgInfo.setText("");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ImageIcon ii = null;
        try {
            BufferedImage bi = ImageIO.read(getClass().getResourceAsStream("/ui/matterhorn-icon-sending.png"));
            ii = new ImageIcon(bi);
        } catch (IOException ex) {
            logger.error("UpdateCheck::Constructor - IOException: " + ex.getMessage());
            label_imgInfo.setVisible(false);
        }
        if(ii != null) {
            label_imgInfo = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
            setTitle("Check for updates");
            setAlwaysOnTop(true);
            setMinimumSize(new java.awt.Dimension(361, 119));
            setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            setUndecorated(true);
            setResizable(false);
            getContentPane().setLayout(new java.awt.GridBagLayout());

            jPanel2.setBackground(new java.awt.Color(200, 200, 200));
            jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel2.setLayout(new java.awt.GridBagLayout());

            jPanel1.setBackground(new java.awt.Color(200, 200, 200));
            jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
            jPanel1.setLayout(new java.awt.GridBagLayout());

            label_imgInfo.setIcon(ii);
            label_imgInfo.setText("LOGO");
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
            jPanel1.add(label_imgInfo, gridBagConstraints);
        } else {
            label_imgInfo = new javax.swing.JLabel();
            label_imgInfo.setVisible(false);
        }

        jLabel2.setText("Checking for updates...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_imgInfo;
    // End of variables declaration//GEN-END:variables
}
